# Generated by Django 4.2.7 on 2026-06-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('parent', 'Parent'), ('student', 'Student')], default='staff', max_length=20),
        ),
    ]
