# Generated by Django 4.2.7 on 2026-07-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_address_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'application_number', 'fee_receipt'", max_length=100)),
                ('prefix', models.CharField(blank=True, help_text='Prefix for the generated number', max_length=20)),
                ('current_value', models.PositiveBigIntegerField(default=0)),
                ('increment_by', models.PositiveIntegerField(default=1)),
                ('reset_period', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='never', help_text='When to reset the counter', max_length=20)),
                ('last_reset', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_sequences', to='core.school')),
            ],
            options={
                'verbose_name': 'Number Sequence',
                'verbose_name_plural': 'Number Sequences',
                'db_table': 'number_sequences',
                'unique_together': {('school', 'name')},
            },
        ),
    ]
