# Generated by Django 4.2.7 on 2026-06-30 03:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('walk_in', 'Walk-in'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up Required'), ('converted', 'Converted to Application'), ('lost', 'Lost')], default='new', max_length=20)),
                ('preferred_course', models.CharField(max_length=200)),
                ('expected_start_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_contacted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-enquiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('deferred', 'Deferred')], default='submitted', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_class_grade', models.CharField(blank=True, max_length=50)),
                ('percentage_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage in last qualifying examination', max_digits=5, null=True)),
                ('applied_for_class', models.CharField(max_length=50)),
                ('preferred_stream', models.CharField(blank=True, max_length=100)),
                ('birth_certificate', models.CharField(blank=True, max_length=255)),
                ('transfer_certificate', models.CharField(blank=True, max_length=255)),
                ('mark_sheets', models.CharField(blank=True, max_length=255)),
                ('address_proof', models.CharField(blank=True, max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_phone', models.CharField(blank=True, max_length=17)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_phone', models.CharField(blank=True, max_length=17)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('guardian_phone', models.CharField(blank=True, max_length=17)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='admissions.enquiry')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
