# Generated by Django 4.2.7 on 2026-07-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_numbersequence'),
        ('students', '0001_initial'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='father_phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_relationship',
        ),
        migrations.RemoveField(
            model_name='application',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='mother_occupation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='mother_phone',
        ),
        migrations.AddField(
            model_name='application',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.campus'),
        ),
        migrations.AddField(
            model_name='application',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_applications', to='students.guardian'),
        ),
        migrations.AddField(
            model_name='application',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_applications', to='students.guardian'),
        ),
        migrations.AddField(
            model_name='application',
            name='primary_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_applications', to='students.guardian'),
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.school'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='core.campus'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='core.school'),
        ),
        migrations.AlterField(
            model_name='application',
            name='address_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_address_proofs', to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='birth_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_birth_certificates', to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mark_sheets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_mark_sheets', to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transfer_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_transfer_certificates', to='core.attachment'),
        ),
    ]
